version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fast_db
    env_file:
      - .env
    ports:
      - "5433:5432"

  server_1:
    build:
      context: ./
      dockerfile: ./dummy_server/Dockerfile
    container_name: fastapi_server_1
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: ["/backend/docker/app.sh"]
    ports:
      - "9000:8000"

  server_2:
    build:
      context: ./
      dockerfile: ./dummy_server/Dockerfile
    container_name: fastapi_server_2
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: [ "/backend/docker/app.sh" ]
    ports:
      - "9001:8000"

  redis:
    image: redis
    container_name: mutex
    ports:
      - "6379:6379"