"""initial

Revision ID: 924b67e13dfe
Revises: 
Create Date: 2023-09-24 14:27:33.833208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924b67e13dfe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('message', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('message', 'name')
    # ### end Alembic commands ###
