"""index for name

Revision ID: f3a221b2d280
Revises: 6b22999bffb6
Create Date: 2023-09-30 22:24:13.159162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a221b2d280'
down_revision: Union[str, None] = '6b22999bffb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_message_name'), 'message', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_name'), table_name='message')
    # ### end Alembic commands ###
